# Configuration for the landing page hosted via Github pages 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: AIT Rapid Deployment Platform
#description: TBA
show_downloads: false
